-- Seed data for default_price_book_items — the shared starter Pricing Book
-- every new organization's own price book is copied from on signup.
-- Generated from the Vicello master price book, "UPDATED PRICE BOOK 24TH AUGUST 2026" (556 items).
truncate table default_price_book_items;
insert into default_price_book_items (calc, section, category, name, rate, unit, sort_order) values
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 16mm White HMR', 502, 'm', 0),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 16mm Black HMR', 505, 'm', 1),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 16mm Polytec Matt', 513, 'm', 2),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 16mm Polytec Woodmatt / Smooth / Ravine', 528, 'm', 3),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 18mm Polytec Boston Oak Range', 535, 'm', 4),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - NAV Elements & Earth G2S / 18mm Tesrol Supeclean G1S', 563, 'm', 5),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - NAV Urban', 578, 'm', 6),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 18mm Polytec Vennette / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 583, 'm', 7),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 18mm Polyurethane Flat Profile', 593, 'm', 8),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 21mm Polyurethane Flat Panel', 596, 'm', 9),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 628, 'm', 10),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 19mm Blackbutt Veneer G1S  Clear Polyurethane', 647, 'm', 11),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 18mm Polyurethane Shaker Profile Rail 40mm + (3mm recess)', 648, 'm', 12),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 21mm Polyurethane Shaker Profile (5mm recess) Including 500 & 600 Series', 658, 'm', 13),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 19mm Spotted Gum 19mm G1S', 668, 'm', 14),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 19mm American Walnut w/ Clear Polyurethane  (crown cut)', 678, 'm', 15),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 18mm Polytec Surrano Doors From Polytec', 703, 'm', 16),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 25mm Polyurethane Scandinavian Profile', 713, 'm', 17),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 18mm Eveneer Fango G2S', 719, 'm', 18),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 19mm Naveneer G2S', 726, 'm', 19),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 32mm Polyurethane Shaker Profile (5mm recess) Argyle doors Collection 6', 763, 'm', 20),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - Timberwood 16mm Stylex Carcass with 18mm UV Coated Doors (Alfresco Material)', 848, 'm', 21),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 13mm Polytec Compact Laminate With No Frame (With Stlyex Internal Carcass)', 880, 'm', 22),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 19mm Cabinetti American Walnut Veneer G1S w/ Clear Polyurethane  (crown cut)', 878, 'm', 23),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 13mm Polytec Compact Laminate With Frame 2mm x 55mm Black Anodised (With Stlyex Internal Carcass)', 953, 'm', 24),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 22mm Farmers Doors Bleached American Oak (40mm Shaker in Matching Veneer & Farmers water based coating)', 1122, 'm', 25),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 22mm Farmers Doors Weathered Slimline Oak Stained (3mm recess)', 1133, 'm', 26),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 22mm Farmers Doors BORD Verdi Reconstituted Veneer (40mm Shaker in Matching Veneer & Farmers water based coating)', 1100, 'm', 27),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 27mm Farmers Doors Weathered Slimline Oak Stained (8mm recess)', 1128, 'm', 28),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Cabinet - 22mm Farmers Doors Elton Romano Reconstituted Veneer (40mm Shaker in Matching Veneer & Farmers water based coating)', 1142, 'm', 29),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 16mm White HMR (1x ADJ SHELF)', 468, 'm', 30),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 16mm Natural Cotton HMR (1x ADJ SHELF)', 501, 'm', 31),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 16mm Polytec Matt (1x ADJ SHELF)', 508, 'm', 32),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 16m Polytec Woodmatt / Smooth / Ravine  (1x ADJ SHELF)', 570, 'm', 33),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 18mm Polytec Woodmatt (Boston Oak Collection) (1x ADJ SHELF)', 594, 'm', 34),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 25mm Polytec Smooth (1x ADJ SHELF)', 622, 'm', 35),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 25mm Polytec Woodmatt (1x ADJ SHELF)', 647, 'm', 36),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 32mm Polytec Woodmatt (1x ADJ SHELF)', 695, 'm', 37),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - NAV Elements & Earth G2S', 708, 'm', 38),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 32mm Polytec Ravine (1x ADJ SHELF)', 762, 'm', 39),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 18m NAV Urban (1x ADJ SHELF)', 768, 'm', 40),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 18m NAV Urban Diamond (1x ADJ SHELF)', 790, 'm', 41),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 18mm Polyurethane Flat Profile (1x ADJ SHELF)', 864, 'm', 42),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 25mm Polyurethane Flat Profile (1x ADJ SHELF)', 885, 'm', 43),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 953, 'm', 44),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving- 19mm Blackbutt Veneer G1S  Clear Polyurethane', 1031, 'm', 45),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 19mm Spotted Gum 19mm G1S', 1074, 'm', 46),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 19mm American Walnut w/ Clear Polyurethane  (crown cut)', 1145, 'm', 47),
  ('LM', 'Lineal metre items', 'Base cabinets up to 650mm d x 900mm h', 'Base Open cabinet with shelving - 19mm Naveneer G2S (1x ADJ SHELF)', 1344, 'm', 48),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 16mm White HMR', 533, 'm', 49),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 16mm Black HMR', 538, 'm', 50),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 16mm Polytec Matt', 551, 'm', 51),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 16mm Polytec Woodmatt / Smooth / Ravine', 578, 'm', 52),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 18mm Polytec Boston Oak Range', 589, 'm', 53),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - NAV Elements & Earth G2S / 18mm Tesrol Supeclean G1S', 638, 'm', 54),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - NAV Urban', 664, 'm', 55),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 18mm Polytec Vennette / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 672, 'm', 56),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 18mm Polyurethane Flat Profile', 681, 'm', 57),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 21mm Polyurethane Flat Panel', 697, 'm', 58),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 744, 'm', 59),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 19mm Blackbutt Veneer G1S  Clear Polyurethane', 778, 'm', 60),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 18mm Polyurethane Shaker Profile Rail 40mm + (3mm recess)', 780, 'm', 61),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 21mm Polyurethane Shaker Profile (5mm recess) Including 500 & 600 Series', 794, 'm', 62),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 19mm Spotted Gum 19mm G1S', 796, 'm', 63),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 18mm Polytec Surrano Doors From Polytec', 827, 'm', 64),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 19mm American Walnut w/ Clear Polyurethane  (crown cut)', 818, 'm', 65),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - Timberwood 16mm Stylex Carcass with 18mm UV Coated Doors (Alfresco Material)', 850, 'm', 66),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 25mm Polyurethane Scandinavian Profile', 887, 'm', 67),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 18mm Eveneer Fango G2S', 905, 'm', 68),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 19mm Naveneer G2S', 913, 'm', 69),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 32mm Polyurethane Shaker Profile (5mm recess) Argyle doors Collection 6', 970, 'm', 70),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 13mm Polytec Compact Laminate With No Frame (With Stlyex Internal Carcass)', 1053, 'm', 71),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 19mm Cabinetti American Walnut Veneer G1S w/ Clear Polyurethane  (crown cut)', 1185, 'm', 72),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 13mm Polytec Compact Laminate With Frame 2mm x 55mm Black Anodised (With Stlyex Internal Carcass)', 1251, 'm', 73),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 22mm Farmers Doors Bleached American Oak (40mm Shaker in Matching Veneer & Farmers water based coating)', 1296, 'm', 74),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 22mm Farmers Doors BORD Verdi Reconstituted Veneer (40mm Shaker in Matching Veneer & Farmers water based coating)', 1338, 'm', 75),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 22mm Farmers Doors Weathered Slimline Oak Stained (3mm recess)', 1250, 'm', 76),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 22mm Farmers Doors Elton Romano Reconstituted Veneer (40mm Shaker in Matching Veneer & Farmers water based coating)', 1281, 'm', 77),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Cabinet - 27mm Farmers Doors Weathered Slimline Oak Stained (8mm recess)', 1300, 'm', 78),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 16mm White HMR (2x ADJ SHELF)', 474, 'm', 79),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 16mm Natural Cotton HMR (2x ADJ SHELF)', 504, 'm', 80),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 16mm Polytec Matt (2x ADJ SHELF)', 510, 'm', 81),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 16m Polytec Woodmatt / Smooth / Ravine  (2x ADJ SHELF)', 569, 'm', 82),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 18mm Polytec Woodmatt (Boston Oak Collection) (2x ADJ SHELF)', 592, 'm', 83),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 25mm Polytec Smooth (2x ADJ SHELF)', 617, 'm', 84),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 25mm Polytec Woodmatt (2x ADJ SHELF)', 640, 'm', 85),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 32mm Polytec Woodmatt (2x ADJ SHELF)', 680, 'm', 86),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - NAV Elements & Earth G2S', 700, 'm', 87),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 32mm Polytec Ravine (2x ADJ SHELF)', 745, 'm', 88),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 18m NAV Urban (2x ADJ SHELF)', 755, 'm', 89),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 18m NAV Urban Diamond (2x ADJ SHELF)', 775, 'm', 90),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 18mm Polyurethane Flat Profile (2x ADJ SHELF)', 849, 'm', 91),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 25mm Polyurethane Flat Profile (2x ADJ SHELF)', 869, 'm', 92),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 929, 'm', 93),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving- 19mm Blackbutt Veneer G1S  Clear Polyurethane', 1004, 'm', 94),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 19mm Spotted Gum 19mm G1S', 1043, 'm', 95),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 19mm American Walnut w/ Clear Polyurethane  (crown cut)', 1110, 'm', 96),
  ('LM', 'Lineal metre items', 'Wall cabinets up to 370mm d x 1000mm h - including underpanel and 30mm shadowline', 'Wall Open cabinet with shelving - 19mm Naveneer G2S (1x ADJ SHELF)', 1295, 'm', 97),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 16mm White HMR', 712, 'm', 98),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 16mm Black HMR', 717, 'm', 99),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 16mm Polytec Matt', 747, 'm', 100),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 16mm Polytec Woodmatt / Smooth / Ravine', 798, 'm', 101),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 18mm Polytec Boston Oak Range', 819, 'm', 102),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - NAV Elements & Earth G2S / 18mm Tesrol Supeclean G1S', 915, 'm', 103),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - NAV Urban', 964, 'm', 104),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 18mm Polytec Vennette / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 982, 'm', 105),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 18mm Polyurethane Flat Profile', 996, 'm', 106),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 21mm Polyurethane Flat Panel', 1026, 'm', 107),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 1118, 'm', 108),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 19mm Blackbutt Veneer G1S  Clear Polyurethane', 1184, 'm', 109),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 19mm Spotted Gum 19mm G1S', 1219, 'm', 110),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 18mm Polyurethane Shaker Profile Rail 40mm + (3mm recess)', 1242, 'm', 111),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 21mm Polyurethane Shaker Profile (5mm recess) Including 500 & 600 Series', 1275, 'm', 112),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 19mm American Walnut w/ Clear Polyurethane  (crown cut)', 1279, 'm', 113),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 18mm Polytec Surrano Doors From Polytec', 1332, 'm', 114),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 18mm Eveneer Fango G2S', 1429, 'm', 115),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 19mm Naveneer G2S', 1444, 'm', 116),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 25mm Polyurethane Scandinavian Profile', 1458, 'm', 117),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 32mm Polyurethane Shaker Profile (5mm recess) Argyle doors Collection 6', 1562, 'm', 118),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - Timberwood 16mm Stylex Carcass with 18mm UV Coated Doors (Alfresco Material)', 1827, 'm', 119),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 13mm Polytec Compact Laminate With No Frame (With Stlyex Internal Carcass)', 1909, 'm', 120),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 19mm Cabinetti American Walnut Veneer G1S w/ Clear Polyurethane  (crown cut)', 1982, 'm', 121),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 13mm Polytec Compact Laminate With Frame 2mm x 55mm Black Anodised (With Stlyex Internal Carcass)', 2168, 'm', 122),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 22mm Farmers Doors Bleached American Oak (40mm Shaker in Matching Veneer & Farmers water based coating)', 2041, 'm', 123),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 22mm Farmers Doors Elton Romano Reconstituted Veneer (40mm Shaker in Matching Veneer & Farmers water based coating)', 2153, 'm', 124),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 22mm Farmers Doors BORD Verdi Reconstituted Veneer (40mm Shaker in Matching Veneer & Farmers water based coating)', 2115, 'm', 125),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 22mm Farmers Doors Weathered Slimline Oak Stained (3mm recess)', 2317, 'm', 126),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Cabinet - 27mm Farmers Doors Weathered Slimline Oak Stained (8mm recess)', 2397, 'm', 127),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 16mm White HMR (5x ADJ SHELF)', 603, 'm', 128),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 16mm Natural Cotton HMR (5x ADJ SHELF)', 706, 'm', 129),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 16mm Polytec Matt (5x ADJ SHELF)', 727, 'm', 130),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 16m Polytec Woodmatt / Smooth / Ravine  (5x ADJ SHELF)', 924, 'm', 131),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 18mm Polytec Woodmatt (Boston Oak Collection) (5x ADJ SHELF)', 1001, 'm', 132),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 25mm Polytec Smooth (5x ADJ SHELF)', 1092, 'm', 133),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 25mm Polytec Woodmatt (5x ADJ SHELF)', 1169, 'm', 134),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 32mm Polytec Woodmatt (5x ADJ SHELF)', 1310, 'm', 135),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - NAV Elements & Earth G2S', 1368, 'm', 136),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 32mm Polytec Ravine (5x ADJ SHELF)', 1532, 'm', 137),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 18m NAV Urban (5x ADJ SHELF)', 1554, 'm', 138),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 18m NAV Urban Diamond (5x ADJ SHELF)', 1624, 'm', 139),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 18mm Polyurethane Flat Profile (5x ADJ SHELF)', 1652, 'm', 140),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 25mm Polyurethane Flat Profile (5x ADJ SHELF)', 1723, 'm', 141),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 2142, 'm', 142),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving- 19mm Blackbutt Veneer G1S  Clear Polyurethane', 2392, 'm', 143),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 19mm Spotted Gum 19mm G1S', 2526, 'm', 144),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 19mm American Walnut w/ Clear Polyurethane  (crown cut)', 2752, 'm', 145),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Tall Open cabinet with shelving - 19mm Naveneer G2S (5x ADJ SHELF)', 3382, 'm', 146),
  ('LM', 'Lineal metre items', 'Tall cabinets up to 650mm d x 2700mm h - including 30mm shadowline', 'Angled shoe shelf in open cabinets (Per cabinet)', 685, 'm', 147),
  ('LM', 'Lineal metre items', 'Bulkhead - Up To 350mm High (1 = 1X LM)', 'Bulkhead - White HMR / Raw MDF', 134, 'm', 148),
  ('LM', 'Lineal metre items', 'Bulkhead - Up To 350mm High (1 = 1X LM)', 'Bulkhead - Black HMR', 136, 'm', 149),
  ('LM', 'Lineal metre items', 'Bulkhead - Up To 350mm High (1 = 1X LM)', 'Bulkhead - Polytec Matt', 139, 'm', 150),
  ('LM', 'Lineal metre items', 'Bulkhead - Up To 350mm High (1 = 1X LM)', 'Bulkhead - Polytec Woodmatt / Smooth / Ravine', 145, 'm', 151),
  ('LM', 'Lineal metre items', 'Bulkhead - Up To 350mm High (1 = 1X LM)', 'Bulkhead - Polytec 18mm Polytec Boston Oak Range', 148, 'm', 152),
  ('LM', 'Lineal metre items', 'Bulkhead - Up To 350mm High (1 = 1X LM)', 'Bulkhead - NAV Elements & Earth G2S', 154, 'm', 153),
  ('LM', 'Lineal metre items', 'Bulkhead - Up To 350mm High (1 = 1X LM)', 'Bulkhead - NAV Urban', 158, 'm', 154),
  ('LM', 'Lineal metre items', 'Bulkhead - Up To 350mm High (1 = 1X LM)', 'Bulkhead - 18mm Polytec Vennette & Tesrol Supeclean  / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 160, 'm', 155),
  ('LM', 'Lineal metre items', 'Bulkhead - Up To 350mm High (1 = 1X LM)', 'Bulkhead - 18mm Polyurethane Flat Profile', 163, 'm', 156),
  ('LM', 'Lineal metre items', 'Bulkhead - Up To 350mm High (1 = 1X LM)', 'Bulkhead - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 184, 'm', 157),
  ('LM', 'Lineal metre items', 'Bulkhead - Up To 350mm High (1 = 1X LM)', 'Bulkhead - 19mm Blackbutt Veneer G1S', 193, 'm', 158),
  ('LM', 'Lineal metre items', 'Bulkhead - Up To 350mm High (1 = 1X LM)', 'Bulkhead - 19mm American Walnut w/ Clear Polyurethane  (crown cut)', 206, 'm', 159),
  ('LM', 'Lineal metre items', 'Bulkhead - Up To 350mm High (1 = 1X LM)', 'Bulkhead - 19mm Naveneer G2S', 225, 'm', 160),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'Bulkhead - White HMR / Raw MDF', 158, 'm', 161),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'Bulkhead - Black HMR', 160, 'm', 162),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'Bulkhead - Polytec Matt', 169, 'm', 163),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'Bulkhead - Polytec Woodmatt / Smooth / Ravine', 186, 'm', 164),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'Bulkhead - Polytec 18mm Polytec Boston Oak Range', 193, 'm', 165),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'Bulkhead - NAV Elements & Earth G2S', 208, 'm', 166),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'Bulkhead - NAV Urban', 217, 'm', 167),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'Bulkhead - 18mm Polytec Vennette & Tesrol Supeclean  / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 221, 'm', 168),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'Bulkhead - 18mm Polyurethane Flat Profile', 278, 'm', 169),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'Bulkhead - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 281, 'm', 170),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'Bulkhead - 19mm Blackbutt Veneer G1S', 302, 'm', 171),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'Bulkhead - 19mm American Walnut w/ Clear Polyurethane  (crown cut)', 334, 'm', 172),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'Bulkhead - 19mm Naveneer G2S', 380, 'm', 173),
  ('LM', 'Lineal metre items', 'Mitred Bulkhead Small - (1 = 1X LM)', 'AC Grill outs to mitred bulkheads (Sprayed in a mathcing colour)', 1120, 'm', 174),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall Panelling - White HMR', 212, 'm', 175),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall Panelling - Black HMR', 215, 'm', 176),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall Panelling - Polytec Matt', 246, 'm', 177),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall Panelling - Polytec Woodmatt / Smooth / Ravine', 299, 'm', 178),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall Panelling - Polytec 18mm Polytec Boston Oak Range', 321, 'm', 179),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall Panelling - NAV Elements & Earth G2S', 369, 'm', 180),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall Panelling - NAV Urban', 396, 'm', 181),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall Panelling - 18mm Polytec Vennette & Tesrol Supeclean  / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 410, 'm', 182),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall Panelling - 18mm Polyurethane Flat Profile', 498, 'm', 183),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall Panelling - 18mm Polyurethane shaker Profile', 528, 'm', 184),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall Panelling - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 581, 'm', 185),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall Panelling - 19mm Blackbutt Veneer G1S', 649, 'm', 186),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall panelling - 25mm Scandinavian Profile', 692, 'm', 187),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall panelling - American Walnut w/ Clear Polyurethane  (crown cut)', 749, 'm', 188),
  ('LM', 'Lineal metre items', 'Wall Pannelling 2700mm H x 1000mm W', 'Wall Panelling - 19mm Naveneer G2S', 892, 'm', 189),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 16mm White HMR', 626, 'ea', 190),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 16mm Black HMR', 629, 'ea', 191),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 16mm Polytec Matt', 637, 'ea', 192),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 16mm Polytec Woodmatt / Smooth / Ravine', 690, 'ea', 193),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 18mm Polytec Boston Oak Range', 661, 'ea', 194),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - NAV Elements & Earth G2S', 675, 'ea', 195),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - NAV Urban', 683, 'ea', 196),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 18mm Polytec Vennette & 18mm Tesrol Supeclean G1S   / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 689, 'ea', 197),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 18mm Polyurethane Flat Profile', 702, 'ea', 198),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 21mm Polyurethane Flat Panel', 741, 'ea', 199),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 773, 'ea', 200),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 17mm Euro Birch Full-Rotary Cr DGB', 786, 'ea', 201),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 18mm Polyurethane Shaker Profile Rail 40mm + (3mm recess)', 813, 'ea', 202),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 19mm Blackbutt Veneer G1S / Euro Birch Semi - Rotary CR DGB', 759, 'ea', 203),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 21mm Polyurethane Shaker Profile (5mm recess) Including 500 & 600 Series', 813, 'ea', 204),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 19mm Spotted Gum Veneer G1S w/ Clear Polyurethane  (crown cut)', 789, 'ea', 205),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 19mm American Walnut w/ Clear Polyurethane  (crown cut)', 808, 'ea', 206),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 19mm Naveneer G2S', 838, 'ea', 207),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 25mm Polyurethane Scandinavian Profile', 840, 'ea', 208),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 18mm Eveneer Fango G2S', 859, 'ea', 209),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 22mm Farmers Doors Weathered Slimline Oak Stained (3mm recess)', 879, 'ea', 210),
  ('QTY', 'Per-unit items', 'Appliance Tower up to 600mm d x 2700mm h   - including 2x drawers below ovens (1x 600mm Oven Tower)', 'Tall Appliance Cabinet - 27mm Farmers Doors Weathered Slimline Oak Stained (3mm recess)', 905, 'ea', 211),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 16mm White HMR', 202, 'ea', 212),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 16mm Black HMR', 208, 'ea', 213),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 16mm Polytec Matt', 235, 'ea', 214),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 16mm Polytec Woodmatt / Smooth / Ravine', 287, 'ea', 215),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 18mm Polytec Boston Oak Range', 309, 'ea', 216),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - NAV Elements & Earth G2S', 355, 'ea', 217),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - NAV Urban', 381, 'ea', 218),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 18mm Polytec Vennette & 18mm Tesrol Supeclean G1S  / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 396, 'ea', 219),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 18mm Polyurethane Flat Profile', 514, 'ea', 220),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 615, 'ea', 221),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 19mm Blackbutt Veneer G1S / American Walnut w/ Clear Polyurethane  (crown cut)', 686, 'ea', 222),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 18mm Polyurethane Shaker Profile Rail 40mm + (3mm recess)', 699, 'ea', 223),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 25mm Polyurethane Scandinavian Profile', 705, 'ea', 224),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 19mm Spotted Gum Veneer G1S w/ Clear Polyurethane  (crown cut)', 722, 'ea', 225),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 21mm Polyurethane Shaker Profile (5mm recess) Including 500 & 600 Series', 738, 'ea', 226),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 19mm Naveneer G2S', 871, 'ea', 227),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 18mm Eveneer Fango G2S', 937, 'ea', 228),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - Timberwood 18mm UV Coated Doors (Alfresco Material)', 765, 'ea', 229),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 22mm Farmers Doors Weathered Slimline Oak Stained (3mm recess)', 1215, 'ea', 230),
  ('QTY', 'Per-unit items', 'Bar Back Panel (1x Panel 3000mm x 880mm)', 'Bar back - 22mm Farmers Doors Weathered Slimline Oak Stained (8mm recess)', 1255, 'ea', 231),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 16mm White HMR', 150, 'ea', 232),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 16mm Black HMR', 152, 'ea', 233),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 16mm Polytec Matt', 157, 'ea', 234),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel- 16mm Polytec Woodmatt / Smooth / Ravine', 169, 'ea', 235),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 18mm Polytec Boston Oak Range', 174, 'ea', 236),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - NAV Elements & Earth G2S', 185, 'ea', 237),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - NAV Urban', 191, 'ea', 238),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 18mm Polytec Vennette & 18mm Tesrol Supeclean G1S  / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 194, 'ea', 239),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 18mm Polyurethane Flat Profile', 221, 'ea', 240),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - Timberwood 18mm UV Coated Doors (Alfresco Material)', 233, 'ea', 241),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 244, 'ea', 242),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 19mm Blackbutt Veneer G1S / American Walnut w/ Clear Polyurethane  (crown cut)', 259, 'ea', 243),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 18mm Polyurethane Shaker Profile Rail 40mm + (3mm recess)', 263, 'ea', 244),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 13mm Polytec Compact Laminate (No Frame)', 262, 'ea', 245),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 19mm Spotted Gum Veneer G1S w/ Clear Polyurethane  (crown cut)', 268, 'ea', 246),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 21mm Polyurethane Shaker Profile (5mm recess) Including 500 & 600 Series', 271, 'ea', 247),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 19mm Naveneer G2S', 301, 'ea', 248),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 18mm Eveneer Fango G2S', 316, 'ea', 249),
  ('QTY', 'Per-unit items', 'Base End Panels 18mm - 22mm (1x Panel 650mm x 900mm)', 'Base End Panel - 22mm Farmers Doors Weathered Slimline Oak Stained (3mm recess)', 455, 'ea', 250),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel - 25mm White HMR', 155, 'ea', 251),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel - 25mm Black HMR', 158, 'ea', 252),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel - 25mm Polytec Matt', 164, 'ea', 253),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel- 25mm Polytec Woodmatt / Smooth / Ravine', 185, 'ea', 254),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel - 25mm Polytec Boston Oak Range', 187, 'ea', 255),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel -  25mm NAV Elements & Earth G2S', 196, 'ea', 256),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel -  25mm NAV Urban', 207, 'ea', 257),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel -  25mm NAV Urban Diamond', 211, 'ea', 258),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel - 25mm Polytec Vennette & 18mm Tesrol Supeclean G1S / Elton Group Evenex Sincro', 243, 'ea', 259),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel - 25mm Polyurethane Flat Profile', 245, 'ea', 260),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel - 25mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 259, 'ea', 261),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel -25mm Blackbutt Veneer G1S / American Walnut w/ Clear Polyurethane  (crown cut)', 268, 'ea', 262),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel - 25mm Polyurethane Scandinavian Profile', 257, 'ea', 263),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel - 25mm Polyurethane Shaker Profile Rail 40mm + (3mm recess)', 275, 'ea', 264),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel - 25mm Spotted Gum Veneer G1S w/ Clear Polyurethane  (crown cut)', 269, 'ea', 265),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel - 26mm Naveneer G2S', 313, 'ea', 266),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel - 25mm Eveneer Fango G2S', 350, 'ea', 267),
  ('QTY', 'Per-unit items', '25mm base end panels (1x Panel 650mm x 900mm)', 'Base End Panel - 25mm Farmers Doors Weathered Slimline Oak Stained (8mm recess)', 500, 'ea', 268),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 16mm White HMR', 146, 'ea', 269),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 16mm Black HMR', 148, 'ea', 270),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 16mm Polytec Matt', 150, 'ea', 271),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 16mm Polytec Woodmatt / Smooth / Ravine', 157, 'ea', 272),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels  - 18mm Polytec Boston Oak Range', 160, 'ea', 273),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - NAV Elements & Earth G2S', 168, 'ea', 274),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - NAV Urban', 171, 'ea', 275),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 18mm Polytec Vennette & 18mm Tesrol Supeclean G1S  / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 173, 'ea', 276),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 18mm Polyurethane Flat Profile', 190, 'ea', 277),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - Timberwood 18mm UV Coated Doors (Alfresco Material)', 197, 'ea', 278),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 204, 'ea', 279),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 19mm Blackbutt Veneer G1S / American Walnut w/ Clear Polyurethane  (crown cut)', 213, 'ea', 280),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 18mm Polyurethane Shaker Profile Rail 40mm + (3mm recess)', 215, 'ea', 281),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 13mm Polytec Compact Laminate (No Frame)', 215, 'ea', 282),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 19mm Spotted Gum Veneer G1S w/ Clear Polyurethane  (crown cut)', 218, 'ea', 283),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 21mm Polyurethane Shaker Profile (5mm recess) Including 500 & 600 Series', 220, 'ea', 284),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 19mm Naveneer G2S', 239, 'ea', 285),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 18mm Eveneer Fango G2S', 248, 'ea', 286),
  ('QTY', 'Per-unit items', 'Wall End Panels (1x Panel 370mm x 1000mm)', 'Wall End Panels - 22mm Farmers Doors Weathered Slimline Oak Stained (3mm recess)', 398, 'ea', 287),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 16mm White HMR', 173, 'ea', 288),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 16mm Black HMR', 175, 'ea', 289),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 16mm Polytec Matt', 195, 'ea', 290),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 16mm Polytec Woodmatt / Smooth / Ravine', 229, 'ea', 291),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels  - 18mm Polytec Boston Oak Range', 243, 'ea', 292),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - NAV Elements & Earth G2S', 274, 'ea', 293),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - NAV Urban', 291, 'ea', 294),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 18mm Polytec Vennette & 18mm Tesrol Supeclean G1S  / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 301, 'ea', 295),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 18mm Polyurethane Flat Profile', 380, 'ea', 296),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - Timberwood 18mm UV Coated Doors (Alfresco Material)', 415, 'ea', 297),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 446, 'ea', 298),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 19mm Blackbutt Veneer G1S / American Walnut w/ Clear Polyurethane  (crown cut)', 490, 'ea', 299),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 18mm Polyurethane Shaker Profile Rail 40mm + (3mm recess)', 502, 'ea', 300),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 13mm Polytec Compact Laminate (No Frame)', 503, 'ea', 301),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 19mm Spotted Gum Veneer G1S w/ Clear Polyurethane  (crown cut)', 515, 'ea', 302),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 21mm Polyurethane Shaker Profile (5mm recess) Including 500 & 600 Series', 525, 'ea', 303),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 19mm American Walnut w/ Clear Polyurethane  (crown cut)', 555, 'ea', 304),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 19mm Naveneer G2S', 613, 'ea', 305),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 18mm Eveneer Fango G2S', 657, 'ea', 306),
  ('QTY', 'Per-unit items', 'Tall End Panels 18mm - 19mm - 21mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 22mm Farmers Doors Weathered Slimline Oak Stained (3mm recess)', 898, 'ea', 307),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 25mm White HMR', 187, 'ea', 308),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 25mm Black HMR', 190, 'ea', 309),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 25mm Polytec Matt', 214, 'ea', 310),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 25mm Polytec Woodmatt / Smooth / Ravine & 25mm Polytec Boston Oak Range', 273, 'ea', 311),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 25mm NAV Elements & Earth G2S', 322, 'ea', 312),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 25mm Polyurethane Flat Profile', 351, 'ea', 313),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 25mm NAV Urban', 357, 'ea', 314),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 25mm Polytec Vennette & 18mm Tesrol Supeclean G1S  / 25mm Navurban Diamond Finish / 25mm Elton Group Evenex Sincro', 371, 'ea', 315),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 25mm Polyurethane Shaker Profile Rail 40mm + (3mm recess)', 420, 'ea', 316),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 26mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 490, 'ea', 317),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 26mm Blackbutt Veneer G1S / American Walnut w/ Clear Polyurethane  (crown cut)', 518, 'ea', 318),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 26mm Spotted Gum Veneer G1S w/ Clear Polyurethane  (crown cut)', 522, 'ea', 319),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 26mm American Walnut Veneer G1S w/ Clear Polyurethane  (crown cut)', 572, 'ea', 320),
  ('QTY', 'Per-unit items', 'Tall End Panels 25mm - 26mm (1x Panel 650mm x 2700mm)', 'Tall End Panels - 26mm Naveneer G2S', 674, 'ea', 321),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 32mm - 33mm (1x 1000mm x 650mm)', 'Square edge benchtop  32mm - White HMR (2x 16mm panels screwed together and edged in thicker edge tape)', 217, 'ea', 322),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 32mm - 33mm (1x 1000mm x 650mm)', 'Square edge benchtop  32mm - Black HMR (2x 16mm panels screwed together and edged in thicker edge tape)', 220, 'ea', 323),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 32mm - 33mm (1x 1000mm x 650mm)', 'Square edge benchtop  33mm - Polytec Matt / Polytec Woodmatt / Smooth / Ravine', 258, 'ea', 324),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 32mm - 33mm (1x 1000mm x 650mm)', 'Square edge benchtop  32mm - NAV Elements & Earth G2S', 270, 'ea', 325),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 32mm - 33mm (1x 1000mm x 650mm)', 'Square edge benchtop  33mm - NAV Urban', 280, 'ea', 326),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 32mm - 33mm (1x 1000mm x 650mm)', 'Square edge benchtop  33mm - NAV Urban Diamond / Tesrol Superclean', 287, 'ea', 327),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 32mm - 33mm (1x 1000mm x 650mm)', 'Square edge benchtop  33mm - Polyurethane Flat Profile', 318, 'ea', 328),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 32mm - 33mm (1x 1000mm x 650mm)', 'Square edge benchtop  33mm - American Oak Veneer w/ Polyurethane', 338, 'ea', 329),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 32mm - 33mm (1x 1000mm x 650mm)', 'Square edge benchtop  33mm - Black Butt Veneer w/ Polyurethane', 349, 'ea', 330),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 32mm - 33mm (1x 1000mm x 650mm)', 'Square edge benchtop  33mm Spotted Gum Veneer G1S w/ Clear Polyurethane  (crown cut)', 351, 'ea', 331),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 32mm - 33mm (1x 1000mm x 650mm)', 'Square edge benchtop  33mm American Walnut Veneer G1S w/ Clear Polyurethane  (crown cut)', 355, 'ea', 332),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 32mm - 33mm (1x 1000mm x 650mm)', 'Square edge benchtop  33mm Naveneer', 398, 'ea', 333),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 38mm - 50mm (1x 1000mm x 650mm)', 'Square edge benchtop  38mm - 50mm - White HMR', 227, 'ea', 334),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 38mm - 50mm (1x 1000mm x 650mm)', 'Square edge benchtop  38mm - 50mm - Black HMR', 230, 'ea', 335),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 38mm - 50mm (1x 1000mm x 650mm)', 'Square edge benchtop  38mm - 50mm - Polytec Matt / Polytec Woodmatt / Smooth / Ravine', 268, 'ea', 336),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 38mm - 50mm (1x 1000mm x 650mm)', 'Square edge benchtop  38mm - 50mm - NAV Elements & Earth G2S', 280, 'ea', 337),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 38mm - 50mm (1x 1000mm x 650mm)', 'Square edge benchtop  38mm - 50mm - NAV Urban', 290, 'ea', 338),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 38mm - 50mm (1x 1000mm x 650mm)', 'Square edge benchtop  38mm - 50mm - NAV Urban Diamond / Tesrol Superclean', 297, 'ea', 339),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 38mm - 50mm (1x 1000mm x 650mm)', 'Square edge benchtop  38mm - 50mm - Polyurethane Flat Profile', 328, 'ea', 340),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 38mm - 50mm (1x 1000mm x 650mm)', 'Square edge benchtop  38mm - 50mm - American Oak Veneer w/ Polyurethane', 348, 'ea', 341),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 38mm - 50mm (1x 1000mm x 650mm)', 'Square edge benchtop  38mm - 50mm - Black Butt Veneer w/ Polyurethane', 359, 'ea', 342),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 38mm - 50mm (1x 1000mm x 650mm)', 'Square edge benchtop  38mm - 50mm Spotted Gum Veneer G1S w/ Clear Polyurethane  (crown cut)', 361, 'ea', 343),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 38mm - 50mm (1x 1000mm x 650mm)', 'Square edge benchtop  38mm - 50mm American Walnut Veneer G1S w/ Clear Polyurethane  (crown cut)', 365, 'ea', 344),
  ('QTY', 'Per-unit items', 'Sqaure Edge Benchtops 38mm - 50mm (1x 1000mm x 650mm)', 'Square edge benchtop  38mm - 50mm Naveneer', 408, 'ea', 345),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - White HMR', 724, 'ea', 346),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - Black HMR', 727, 'ea', 347),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - Polytec Matt', 743, 'ea', 348),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - Polytec Woodmatt / Smooth / Ravine', 770, 'ea', 349),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - Polytec Boston Oak Range', 782, 'ea', 350),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - NAV Elements & Earth G2S / Tesrol Supeclean G1S', 833, 'ea', 351),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - Nav Urban', 859, 'ea', 352),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - 18mm Polytec Vennette / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 869, 'ea', 353),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - 18mm Polyurethane Flat', 878, 'ea', 354),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - 21mm Polyurethane Flat', 895, 'ea', 355),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - 19mm American Oak Veneer w/ Polyurethane', 942, 'ea', 356),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - Black Butt Veneer w/ Polyurethane', 976, 'ea', 357),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels & Underpanel - Spotted Gum Veneer G1S w/ Clear Polyurethane  (crown cut)', 995, 'ea', 358),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels & Underpanel - American Walnut Veneer G1S w/ Clear Polyurethane  (crown cut)', 1027, 'ea', 359),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet 1000mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - 19mm Naveneer G2S', 1115, 'ea', 360),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - White HMR', 774, 'ea', 361),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - Black HMR', 777, 'ea', 362),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - Polytec Matt', 793, 'ea', 363),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - Polytec Woodmatt / Smooth / Ravine', 820, 'ea', 364),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - Polytec Boston Oak Range', 832, 'ea', 365),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - NAV Elements & Earth G2S / Tesrol Supeclean G1S', 883, 'ea', 366),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - Nav Urban', 909, 'ea', 367),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - 18mm Polytec Vennette / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 919, 'ea', 368),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - 18mm Polyurethane Flat', 928, 'ea', 369),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - 21mm Polyurethane Flat', 945, 'ea', 370),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - 19mm American Oak Veneer w/ Polyurethane', 992, 'ea', 371),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - Black Butt Veneer w/ Polyurethane', 1026, 'ea', 372),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels & Underpanel - Spotted Gum Veneer G1S w/ Clear Polyurethane  (crown cut)', 1045, 'ea', 373),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels & Underpanel - American Walnut Veneer G1S w/ Clear Polyurethane  (crown cut)', 1077, 'ea', 374),
  ('QTY', 'Per-unit items', 'Mirror shaving cabinet up to 1500mm w x 900mm h x 180mm d', 'Mirrored shaving cabinet w/ end panels - 19mm Naveneer G2S', 1165, 'ea', 375),
  ('QTY', 'Per-unit items', 'Hardware', 'Drawer - Anataro White', 190, 'ea', 376),
  ('QTY', 'Per-unit items', 'Hardware', 'Drawer - Merivo (All Colours)', 230, 'ea', 377),
  ('QTY', 'Per-unit items', 'Hardware', 'Drawer - Legrabox (16mm ONLY)', 285, 'ea', 378),
  ('QTY', 'Per-unit items', 'Hardware', 'Drawer - Movento (Use this drawer for laundry pul out shelf or pul out shelf appliance cabinet)', 330, 'ea', 379),
  ('QTY', 'Per-unit items', 'Hardware', 'Drawer - Merivo Push to Open', 245, 'ea', 380),
  ('QTY', 'Per-unit items', 'Hardware', 'Blum Inner Drawer - Latch', 100, 'ea', 381),
  ('QTY', 'Per-unit items', 'Hardware', 'Drawer - Finista Edge Drawer set 93 Matt 500 40Kg', 112, 'ea', 382),
  ('QTY', 'Per-unit items', 'Hardware', 'Drawer - Finista Edge Drawer set 174 Matt 500 40Kg', 123, 'ea', 383),
  ('QTY', 'Per-unit items', 'Hardware', 'Drawer - Finista Edge Drawer set 238 Matt 500 40Kg', 141, 'ea', 384),
  ('QTY', 'Per-unit items', 'Hardware', 'Inner Drawer - Merivo Aluminium Front', 227, 'ea', 385),
  ('QTY', 'Per-unit items', 'Hardware', 'Inner Drawer - Legrabox (16mm ONLY)', 293, 'ea', 386),
  ('QTY', 'Per-unit items', 'Hardware', 'Inner Drawer - Legrabox C with glass front (16mm ONLY)', 310, 'ea', 387),
  ('QTY', 'Per-unit items', 'Hardware', 'TRIO DRAWER HAFELE', 790, 'ea', 388),
  ('QTY', 'Per-unit items', 'Hardware', 'Blum 110 Degree Hinges and Plates  - silver included in LM rate (30x Hinges)', 260, 'ea', 389),
  ('QTY', 'Per-unit items', 'Hardware', 'Blum 110 Degree Hinges and Plates - Onyx (30x Himges)', 285, 'ea', 390),
  ('QTY', 'Per-unit items', 'Hardware', '400mm Ninka 126 Bin drawer (2x 25L Buckets) 1x Blum drawer included in this price', 525, 'ea', 391),
  ('QTY', 'Per-unit items', 'Hardware', '450mm Ninka 126 Bin (2x 32L Buckets) 1x Blum drawer included in this price', 460, 'ea', 392),
  ('QTY', 'Per-unit items', 'Hardware', '500mm Ninka 126 Bin (2x 8L & 1x 32L Bucket) 1x Blum drawer included in this price', 510, 'ea', 393),
  ('QTY', 'Per-unit items', 'Hardware', '600mm Ninka 126 Bin (2x 42L Buckets) 1x Blum drawer included in this price', 543, 'ea', 394),
  ('QTY', 'Per-unit items', 'Hardware', 'Finista Slide out Under sink pull out twin bin', 277, 'ea', 395),
  ('QTY', 'Per-unit items', 'Hardware', 'Hafele Libero (Electric Bin Opener)', 410, 'ea', 396),
  ('QTY', 'Per-unit items', 'Hardware', 'Metafile frame (Filing Drawer from Lincoln)', 143, 'ea', 397),
  ('QTY', 'Per-unit items', 'Hardware', 'Wingline Bi-fold with top track - One side only', 450, 'ea', 398),
  ('QTY', 'Per-unit items', 'Hardware', 'Hafele HAWA Concepta III Pocket Door system - One side only (Mechanism Only)', 3035, 'ea', 399),
  ('QTY', 'Per-unit items', 'Hardware', 'Hafele Folding Concepta III Door System - Two doors folding one way', 4630, 'ea', 400),
  ('QTY', 'Per-unit items', 'Hardware', 'Lift Up Pocket door system One Mechanism Only', 1110, 'ea', 401),
  ('QTY', 'Per-unit items', 'Hardware', 'HAWA Clipo 36 Sliding door track from Hafele (Door size 1030mm W X 2200MM H) 3x doors', 1690, 'ea', 402),
  ('QTY', 'Per-unit items', 'Hardware', 'Hafele Comfort II 230mm Pull-Out Base Unit (545.53.660) codes are different for LHS or RHS access.', 605, 'ea', 403),
  ('QTY', 'Per-unit items', 'Hardware', 'Hafele Comfort II 300mm Pull-Out Base Unit (545.53.662) codes are different for LHS or RHS access.', 615, 'ea', 404),
  ('QTY', 'Per-unit items', 'Hardware', 'Hafele Comfort II 400mm Pull-Out Base Unit (545.53.664) codes are different for LHS or RHS access.', 688, 'ea', 405),
  ('QTY', 'Per-unit items', 'Hardware', 'Blum HK Aventos NON servo Drive (1 door lift up) 1x Cabinet', 452, 'ea', 406),
  ('QTY', 'Per-unit items', 'Hardware', 'Blum HK Aventos servo Drive (1 door lift up) 1x Cabinet', 1205, 'ea', 407),
  ('QTY', 'Per-unit items', 'Hardware', 'Blum HF Aventos NON servo Drive (2 door lift up) 1x Cabinet', 650, 'ea', 408),
  ('QTY', 'Per-unit items', 'Hardware', 'Blum HF Aventos servo Drive (2 door lift up) 1x Cabinet', 1300, 'ea', 409),
  ('QTY', 'Per-unit items', 'Hardware', '3x Blum Servi Drive HF With 1  standard HF for rangehood cabinet', 2780, 'ea', 410),
  ('QTY', 'Per-unit items', 'Hardware', 'Hafele Wall Bed Bettlift without mattress (Art 271.92.132)', 3600, 'ea', 411),
  ('QTY', 'Per-unit items', 'Hardware', 'Hafele Foldaway bed fitting Teleletto Style (Queen Bed) without mattress (271.91.512)', 4040, 'ea', 412),
  ('QTY', 'Per-unit items', 'Hardware', 'Hafele One Touch (Different to PTO) this mech pops the door out and is installed at the top of the carcass not the edge 315.11.411', 300, 'ea', 413),
  ('QTY', 'Per-unit items', 'Hardware', 'Hafele pull out pantry unit - Convoy Centro  to suit 300mm cab width (O/A Height of 2000-2100mm) - 545.81.501', 1895, 'ea', 414),
  ('QTY', 'Per-unit items', 'Hardware', 'Hafele finetta Flush 50 406.11.285 406.11.690 Double cabinet sliding door pull then slide (2x doors 915 x 1640)', 2850, 'ea', 415),
  ('QTY', 'Per-unit items', 'Hardware', 'Fold down ironing board with stand 1-472-022 Lincoln', 754, 'ea', 416),
  ('QTY', 'Per-unit items', 'Hardware', 'Hafele KABI Fingerprint door and drawer locks 231.98.642', 145, 'ea', 417),
  ('QTY', 'Per-unit items', 'Hardware', 'Acoufelt Opus Range Priced Pm2', 315, 'ea', 418),
  ('QTY', 'Per-unit items', 'Hardware', 'FINISTA Jewllery tray insert Black Velvet 473MM X 600-1000MM (Product Code 7115892 Lincoln Sentry)', 435, 'ea', 419),
  ('QTY', 'Per-unit items', 'Hanging Rails (1x length $19)', '1x hanging rail in laundry', 149, 'ea', 420),
  ('QTY', 'Per-unit items', 'Hanging Rails (1x length $19)', '3-6x hanging rails in robe', 359, 'ea', 421),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Lamination of Pivot Door supplied by Builder / Owner', 1180, 'ea', 422),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Black aluminim wall cabinet doors with glass insert (clear or reeded) Carcass not included 1000mm x 500mm Max height and width', 560, 'ea', 423),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Mirror Polished All Around 600mm Wide x 900mm High (No Substrate)', 355, 'ea', 424),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Mirror Polished All Around 900mm Wide x 1200mm High (No Substrate)', 405, 'ea', 425),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Mirror Polished All Around 600mm Wide x 2400mm High (No Substrate)', 570, 'ea', 426),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Tibo’s pricing for 3mm Solid Brass Frame with Waxed Finish for mirror size 900x1200mm with radius corners', 2500, 'ea', 427),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Jeremey Price for 3mm Stainless Steel Frame w/ Brass look powdercoated finish for the same size above', 1500, 'ea', 428),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Shaker profile using a prefinished board – Leon told me to price as $355 per door/drawer ($60 included for style material)', 420, 'ea', 429),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Mesh Inserts Base & Wall door (Black Perferated Metal From Lincoln) Price per door', 445, 'ea', 430),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Mesh Inserts Tall door (Black Perferated Metal From Lincoln)', 495, 'ea', 431),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Curve Door - Small x1', 2110, 'ea', 432),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Curve Door - Tall x1', 3035, 'ea', 433),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Router LIP Pull Handle into doors', 135, 'ea', 434),
  ('QTY', 'Per-unit items', 'Custom Doors / Aluminium Profiled Doors / Mirrors', 'Inward Swinging Door using Blum hinges and 300mm wide tall cabinet (Tall cabinet to be price in open tall LM rate)', 1005, 'ea', 435),
  ('QTY', 'Per-unit items', 'LED''S & Channels', 'LED extrusion with diffuser rebated. Electrical by owner. Up to 2400mm', 273, 'ea', 436),
  ('QTY', 'Per-unit items', 'LED''S & Channels', 'LED lights from furnware 6mm wide 6m in length (Warm White Or Cool White)', 545, 'ea', 437),
  ('QTY', 'Per-unit items', 'LED''S & Channels', 'Vertical LED lighting with diffuser (Mostly used in wardrobe designs)  (1x length up tp 2400mm)', 273, 'ea', 438),
  ('QTY', 'Per-unit items', 'Integration Services  / Call out Serive', 'Integration Service - Single fridge or freezer', 800, 'ea', 439),
  ('QTY', 'Per-unit items', 'Integration Services  / Call out Serive', 'Integration Service - French door fridge (F&P)', 1100, 'ea', 440),
  ('QTY', 'Per-unit items', 'Integration Services  / Call out Serive', 'Integration Service - Dishwasher 60cm', 600, 'ea', 441),
  ('QTY', 'Per-unit items', 'Integration Services  / Call out Serive', 'Integration Service - Dishdrawer', 650, 'ea', 442),
  ('QTY', 'Per-unit items', 'Integration Services  / Call out Serive', 'Hafele Technician call out to factory to set up hardware with factory team (Must for Bifold pocket system)', 600, 'ea', 443),
  ('QTY', 'Per-unit items', 'Drawer Inserts', 'Lincoln Sentry Orgaline utensil stainless steel 500mm (Product Code: 7103034)', 300, 'ea', 444),
  ('QTY', 'Per-unit items', 'Drawer Inserts', 'Blum ORGA-LINE Cutlery/Utensil Tray 280mm 500NL Stainless Steel (Product Code: 7103025) 2xuntis in one drawer = 550mm wide', 324, 'ea', 445),
  ('QTY', 'Per-unit items', 'Drawer Inserts', 'Blum Ambialine Cutlery Tray 300mm wide (Product Code: 7103177) 2xuntis in one drawer = 600mm wide', 450, 'ea', 446),
  ('QTY', 'Per-unit items', 'Laundry Hampers / 450mm W', 'Symetra, Twin Bin, 2 x 37L Buckets With Pull Out Shelf, To Suit 450mm Cabinet, White (Part Number SYB95.450.237.WH)', 505, 'ea', 447),
  ('QTY', 'Per-unit items', 'Laundry Hampers / 450mm W', 'Laundry Hamper, Hideaway Concelo Laundry range, 1 x 60L hamper (503.55.785)', 627, 'ea', 448),
  ('QTY', 'Per-unit items', 'Laundry Hampers / 450mm W', 'Tanova, designer laundry system, to suit 450mm cabinet, 1 x 65l metal hamper, white (Part Number LTDS45.165L.WH)', 1180, 'ea', 449),
  ('QTY', 'Per-unit items', 'Laundry Hampers / 450mm W', 'Finista Edge Uni-Hamper 450CW 58L White (Product Code: 7116441 )', 526, 'ea', 450),
  ('QTY', 'Per-unit items', 'Laundry Hampers / 600mm W', 'LTDS60.236.WH Furnware Laundry hamper /2x 36L plastic buckets - 600mm W (as per showroom)', 854, 'ea', 451),
  ('QTY', 'Per-unit items', 'Laundry Hampers / 600mm W', 'LTDS60.1100L.WH Furnware Laundry hamper / 1x 100L metal buckets - 600mm W (as per showroom)', 1331, 'ea', 452),
  ('QTY', 'Per-unit items', 'Laundry Hampers / 600mm W', 'TBTL100.DIV.WH.FG Furnware Laundry Basket Divider Only, To Suit 100L Laundry Basket, Metal, White', 219, 'ea', 453),
  ('QTY', 'Per-unit items', 'Laundry Hampers / 600mm W', 'Finista Edge Uni-Hamper 600cw White Multi Fit incl 2 x 43L Hampers (Product Code: 7116442 )', 600, 'ea', 454),
  ('QTY', 'Per-unit items', 'Laundry Chute', 'White HMR laundry chute', 875, 'ea', 455),
  ('QTY', 'Per-unit items', 'Edging Of Carcass & Internal Carcass Upgrade', 'Edge White HMR carcass in edging the match doors and panels (Not veneer) ed. Edge white HMR in woodmatt (Discrection needed)', 490, 'ea', 456),
  ('QTY', 'Per-unit items', 'Edging Of Carcass & Internal Carcass Upgrade', 'Black HMR internal carcass (in lieu of white) (Discrection needed) (30x sheets of 2400x1200)', 1815, 'ea', 457),
  ('QTY', 'Per-unit items', 'Steccawood - Pricing for material to be taken from Polytec Website. Below is labour pricing alone', 'Steccawood w/ spacing', 2205, 'ea', 458),
  ('QTY', 'Per-unit items', 'Steccawood - Pricing for material to be taken from Polytec Website. Below is labour pricing alone', 'Steccawood w/ no spacing', 1685, 'ea', 459),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'Shark edge fingerpull - All pre-finished materials (Price based on standard kitchen)', 815, 'ea', 460),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'Shark edge fingerpull - All MDF polyurethane', 520, 'ea', 461),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'Square edge fingerpull - All pre-finished melamine', 555, 'ea', 462),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'Touch catch (handle less) - all materials ($20 1x PTO)', 76, 'ea', 463),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'Laminate OR Polyurethane mitred drawer handle', 110, 'ea', 464),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'Laminate OR Polyurethane mitred base cabinet door handle', 110, 'ea', 465),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'Laminate OR Polyurethane mitred wall cabinet door handle', 110, 'ea', 466),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'Laminate OR Polyurethane mitred tall cabinet door handle (full height)', 125, 'ea', 467),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'Routed fingerpull - Polyurethane ONLY ($105 1x Handle)', 105, 'ea', 468),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'J-Scoop handles (ea)', 105, 'ea', 469),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'Polyurethane sharkedge external handle x1', 115, 'ea', 470),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'Polyurethane shark edge handle for tall door x1', 120, 'ea', 471),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'Over extended handle detail 16mm thick biscuited to top of door with 10mm rebate below to allow for fingerpull (1X HANDLE)', 165, 'ea', 472),
  ('QTY', 'Per-unit items', 'Joinery Handles', 'Jpull handles for non-poly (Laminated doors not edged sprayed in poly matched color)', 220, 'ea', 473),
  ('QTY', 'Per-unit items', 'Shadow line / Finger rail', 'Shadowline / Finger rail small job', 300, 'ea', 474),
  ('QTY', 'Per-unit items', 'Shadow line / Finger rail', 'Shadowline / Finger rail  medium job', 405, 'ea', 475),
  ('QTY', 'Per-unit items', 'Shadow line / Finger rail', 'Shadowline / Finger rail  large job', 535, 'ea', 476),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - White HMR', 452, 'ea', 477),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - Black HMR', 457, 'ea', 478),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - Polytec Matt', 464, 'ea', 479),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - Polytec Woodmatt / Smooth / Ravine', 482, 'ea', 480),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - Polytec Boston Oak Range', 491, 'ea', 481),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - NAV Elements & Earth G2S / Tesrol Supeclean G1S', 525, 'ea', 482),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - NAV Urban', 544, 'ea', 483),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - Polytec Vennette /  Navurban Diamond Finish / Elton Group Evenex Sincro', 551, 'ea', 484),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - Polyurethane Flat Profile', 565, 'ea', 485),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 602, 'ea', 486),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - Blackbutt Veneer G1S w/ Clear Polyurethane  (crown cut)', 625, 'ea', 487),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - Spotted Gum Veneer G1S w/ Clear Polyurethane', 638, 'ea', 488),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - American Walnut Veneer G1S w/ Clear Polyurethane  (crown cut)', 661, 'ea', 489),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - Naveneer G2S', 722, 'ea', 490),
  ('QTY', 'Per-unit items', '50mm Floating Shelf up to 1200mm Wide W/ HMR Cleats in wall to install', '50mm mitred floating shelf up to 1200mm wide - Eveneer Fango G2S', 716, 'ea', 491),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 16mm White HMR', 414, 'ea', 492),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 16mm Black HMR', 417, 'ea', 493),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 16mm Polytec Matt', 438, 'ea', 494),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 16mm Polytec Woodmatt / Smooth / Ravine', 476, 'ea', 495),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 18mm Polytec Boston Oak Range', 490, 'ea', 496),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - NAV Elements & Earth G2S / Tesrol Supeclean G1S', 560, 'ea', 497),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - NAV Urban', 596, 'ea', 498),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 18mm Polytec Vennette / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 610, 'ea', 499),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 18mm Polyurethane Flat Profile', 634, 'ea', 500),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 21mm Polyurethane Flat Panel', 654, 'ea', 501),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 18mm Polyurethane Shaker Profile Rail 40mm + (3mm recess)', 662, 'ea', 502),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 21mm Polyurethane Shaker Profile (5mm recess) Including 500 & 600 Series', 673, 'ea', 503),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 25mm Polyurethane Scandinavian Profile', 695, 'ea', 504),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 709, 'ea', 505),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 32mm Polyurethane Shaker Profile (5mm recess) Collection 6 doors from Argyle', 720, 'ea', 506),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 19mm Blackbutt Veneer G1S w/ Clear Polyurethane  (crown cut)', 757, 'ea', 507),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 19mm Spotted Gum Veneer G1S w/ Clear Polyurethane  (crown cut)', 782, 'ea', 508),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - Timberwood 16mm Stylex Carcass with 18mm UV Coated Doors (Alfresco Material)', 794, 'ea', 509),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 19mm American Walnut Veneer G1S w/ Clear Polyurethane  (crown cut)', 826, 'ea', 510),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 13mm Polytec Compact Laminate With No Frame to drawer front (With Stlyex Internal Carcass)', 885, 'ea', 511),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 13mm Polytec Compact Laminate With Frame 2mm x 55mm Black Anodised (With Stlyex Internal Carcass)', 910, 'ea', 512),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 18mm Eveneer Fango G2S', 937, 'ea', 513),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 19mm Naveneer G2S', 947, 'ea', 514),
  ('QTY', 'Per-unit items', 'Microwave Pocket - 1x drawer below (600mm Wide)', 'Microwave Pocket - 22mm Farmers Doors Weathered Slimline Oak Stained (3mm recess)', 1010, 'ea', 515),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 16mm White HMR', 516, 'ea', 516),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 16mm Black HMR', 524, 'ea', 517),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 16mm Polytec Matt', 556, 'ea', 518),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 16mm Polytec Woodmatt / Smooth / Ravine', 618, 'ea', 519),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 18mm Polytec Boston Oak Range', 644, 'ea', 520),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - NAV Elements & Earth G2S', 760, 'ea', 521),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - NAV Urban', 819, 'ea', 522),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 18mm Polytec Vennette / 18mm Navurban Diamond Finish / 18mm Elton Group Evenex Sincro', 841, 'ea', 523),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 18mm Polyurethane Flat Profile', 863, 'ea', 524),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 21mm Polyurethane Flat Panel', 890, 'ea', 525),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 19mm American Oak Veneer G1S w/ Clear Polyurethane  (crown cut)', 1006, 'ea', 526),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 18mm Polyurethane Shaker Profile Rail 40mm + (3mm recess)', 1025, 'ea', 527),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 21mm Polyurethane Shaker Profile (5mm recess) Including 500 & 600 Series', 1055, 'ea', 528),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 19mm Blackbutt Veneer G1S w/ Clear Polyurethane  (crown cut)', 1084, 'ea', 529),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 19mm Spotted Gum Veneer G1S w/ Clear Polyurethane  (crown cut)', 1128, 'ea', 530),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 19mm American Walnut Veneer G1S w/ Clear Polyurethane  (crown cut)', 1200, 'ea', 531),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 25mm Polyurethane Scandinavian Profile', 1220, 'ea', 532),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 18mm Eveneer Fango G2S', 1381, 'ea', 533),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors)- 19mm Naveneer G2S', 1399, 'ea', 534),
  ('QTY', 'Per-unit items', 'WIP doors with jamb (2x hinged doors) - Frame To Match Door Material (2700mm H x 150mm D x 1200mm W)', 'WIP doors with jamb (2x hinged doors) - 22mm Farmers Doors Weathered Slimline Oak Stained (3mm recess)', 1470, 'ea', 535),
  ('QTY', 'Per-unit items', 'Hampton / Decorative Items / Custom', '2x 100mm - 150mm Polyurethane shaker profile / v-groove island end panels', 1635, 'ea', 536),
  ('QTY', 'Per-unit items', 'Hampton / Decorative Items / Custom', 'Proud kick to boxed legs only', 1345, 'ea', 537),
  ('QTY', 'Per-unit items', 'Hampton / Decorative Items / Custom', 'Proud kick to back and sides of island', 915, 'ea', 538),
  ('QTY', 'Per-unit items', 'Hampton / Decorative Items / Custom', '1x Tall Mitred panels 50mm - 150mm (Labour only, Material priced as panels above)', 525, 'ea', 539),
  ('QTY', 'Per-unit items', 'Hampton / Decorative Items / Custom', 'Mitred Woodmatt Leg 900mm H X 900mm Deep x 100mm wide (3x panels included in this price)', 570, 'ea', 540),
  ('QTY', 'Per-unit items', 'Hampton / Decorative Items / Custom', 'Labour to biscuit fixed shelf', 310, 'ea', 541),
  ('QTY', 'Per-unit items', 'Hampton / Decorative Items / Custom', 'Return visit to install kickfaces', 300, 'ea', 542),
  ('QTY', 'Per-unit items', 'Hampton / Decorative Items / Custom', 'Mitred rangehood box Labour only (Cost of material is based off LM rate)', 460, 'ea', 543),
  ('QTY', 'Per-unit items', 'Hampton / Decorative Items / Custom', 'Curve - Island bench 900mm high x 450mm wide', 1055, 'ea', 544),
  ('QTY', 'Per-unit items', 'Hampton / Decorative Items / Custom', 'Curve - Rangehood  (Price wall cabinet in LM rate)', 1085, 'ea', 545),
  ('QTY', 'Per-unit items', 'Hampton / Decorative Items / Custom', 'Curve - Scandinavian legs 900mm high x1', 1325, 'ea', 546),
  ('QTY', 'Per-unit items', 'Hampton / Decorative Items / Custom', 'Curve - Tall curved void box laminated (North Kellyville Project)', 1895, 'ea', 547),
  ('QTY', 'Per-unit items', 'Hampton / Decorative Items / Custom', 'ZETR Powerpoint cut outs', 220, 'ea', 548),
  ('QTY', 'Per-unit items', 'MISCELLANEOUS - SERVICE / GOODS', 'Delivery local', 1000, 'ea', 549),
  ('QTY', 'Per-unit items', 'MISCELLANEOUS - SERVICE / GOODS', 'Delivery additional charges for frieght, contractor travel & Accomadation (Bathurst & Sanctuary Point)', 5000, 'ea', 550),
  ('QTY', 'Per-unit items', 'MISCELLANEOUS - SERVICE / GOODS', 'Delivery City or Hard access', 1500, 'ea', 551),
  ('QTY', 'Per-unit items', 'MISCELLANEOUS - SERVICE / GOODS', 'Extra install fee (Price can vary depending on what extras you believe the installer will be doing on site)', 1500, 'ea', 552),
  ('QTY', 'Per-unit items', 'MISCELLANEOUS - SERVICE / GOODS', 'Handles', 100, 'ea', 553),
  ('QTY', 'Per-unit items', 'MISCELLANEOUS - SERVICE / GOODS', 'Extras', 0, 'ea', 554),
  ('QTY', 'Per-unit items', 'MISCELLANEOUS - SERVICE / GOODS', '2 Hour Consultation in Showroom', 500, 'ea', 555);
